from __future__ import annotations

from datetime import datetime
from pathlib import Path

from docx import Document
from docx.oxml.ns import qn
from docx.shared import Inches, Pt


def add_title(document: Document, text: str) -> None:
    paragraph = document.add_paragraph()
    run = paragraph.add_run(text)
    run.bold = True
    run.font.size = Pt(20)
    paragraph.alignment = 1


def add_metadata(document: Document) -> None:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"Generated: {now}",
        "Generated by: Codex automation (Python + python-docx)",
        "Scope: Detailed documentation of the prior environment/tooling/skill upgrade execution",
        "Repository: c:/Users/Saeed/new-chapter",
    ]
    for line in lines:
        p = document.add_paragraph(line)
        p.style = "Intense Quote"


def add_heading(document: Document, text: str, level: int = 1) -> None:
    document.add_heading(text, level=level)


def add_bullet(document: Document, text: str, level: int = 1) -> None:
    paragraph = document.add_paragraph(style=f"List Bullet{'' if level == 1 else f' {level}'}")
    paragraph.add_run(text)


def add_numbered(document: Document, text: str, level: int = 1) -> None:
    paragraph = document.add_paragraph(style=f"List Number{'' if level == 1 else f' {level}'}")
    paragraph.add_run(text)


def add_code_block(document: Document, text: str) -> None:
    paragraph = document.add_paragraph()
    run = paragraph.add_run(text)
    run.font.name = "Consolas"
    run._element.rPr.rFonts.set(qn("w:eastAsia"), "Consolas")
    run.font.size = Pt(9)


def add_paragraph(document: Document, text: str) -> None:
    document.add_paragraph(text)


def add_file_table(document: Document) -> None:
    rows = [
        (
            ".codex/skills/project-docling-engineer/SKILL.md",
            "New custom project skill",
            "Encodes strong implementation behavior and quality gates",
        ),
        (
            ".codex/skills/project-docling-engineer/references/docling-implementation-guide.md",
            "Docling integration guidance",
            "Keeps analyzer strategy consistent",
        ),
        (
            ".codex/skills/project-docling-engineer/references/engineering-checklist.md",
            "Execution checklist",
            "Reduces ad-hoc coding risk",
        ),
        (
            ".codex/skills/project-docling-engineer/references/docx-rtl-notes.md",
            "RTL DOCX notes",
            "Supports Persian mixed-direction correctness",
        ),
        (
            ".codex/skills/project-docling-engineer/scripts/run_quality_gate.py",
            "Quality gate script",
            "Single-command validation of code health",
        ),
        (
            "AGENTS.md",
            "Project-level skill triggers",
            "Ensures future sessions use the right skills automatically",
        ),
        (
            "pyproject.toml",
            "Expanded tooling config",
            "Adds lint/type/test policy and reproducible dev dependencies",
        ),
        (".pre-commit-config.yaml", "Hook config", "Enforces standards before commit"),
        (
            ".github/workflows/ci.yml",
            "CI workflow",
            "Automates lint/type/test and CLI smoke checks",
        ),
        (
            ".vscode/settings.json",
            "Workspace behavior",
            "Consistent interpreter/testing/ruff behavior",
        ),
        (
            ".vscode/extensions.json",
            "Recommended extensions",
            "Standardized local IDE capabilities",
        ),
        (".vscode/tasks.json", "Task automation", "Fast repeatable local commands"),
        (".vscode/launch.json", "Debug launchers", "One-click run and inspect pipeline"),
        (
            ".devcontainer/devcontainer.json",
            "Container config",
            "Portable environment for other machines",
        ),
        (
            ".devcontainer/Dockerfile",
            "System dependencies",
            "Adds OCR/poppler/runtime libs needed for doc workflows",
        ),
        ("scripts/bootstrap_dev.ps1", "Windows bootstrap", "One command onboarding and setup"),
        ("scripts/bootstrap_dev.sh", "Linux/macOS bootstrap", "Cross-platform reproducibility"),
        (
            "scripts/install_repo_skills.py",
            "Skill installation utility",
            "Copies repo skill into local Codex home",
        ),
        (
            "scripts/install_vscode_extensions.ps1",
            "VS Code extension installer",
            "Automates IDE extension alignment",
        ),
        (
            "docs/tooling-research-notes.md",
            "Web research capture",
            "Documents sources and applied decisions",
        ),
        (
            "docs/implementation-playbook.md",
            "Implementation doctrine",
            "Defines practical engineering sequence",
        ),
        ("docs/multi-machine-setup.md", "Portability guide", "Clear onboarding on new systems"),
        (
            "README.md",
            "Expanded developer guidance",
            "Single entry documentation for usage and workflow",
        ),
        (".gitignore", "Ignore rules", "Avoids noise and generated artifact pollution"),
        (".editorconfig", "Formatting baseline", "Consistent spacing/newlines across tools"),
    ]

    table = document.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    hdr[0].text = "Path"
    hdr[1].text = "What Was Added/Changed"
    hdr[2].text = "Why It Matters"
    for path, what, why in rows:
        cells = table.add_row().cells
        cells[0].text = path
        cells[1].text = what
        cells[2].text = why


def add_action_log_table(document: Document) -> None:
    actions = [
        (
            "A-01",
            "Read system skill docs",
            "Need authoritative installer/creator workflow",
            "Correct skill sequencing",
        ),
        (
            "A-02",
            "List curated skills JSON",
            "Machine-readable inventory required",
            "Identified high-value install targets",
        ),
        (
            "A-03",
            "Install gh-address-comments",
            "Improve PR closure discipline",
            "Skill available globally",
        ),
        (
            "A-04",
            "Install gh-fix-ci",
            "Improve CI diagnosis/fix capability",
            "Skill available globally",
        ),
        ("A-05", "Re-list skills", "Post-install verification", "Confirmed install state"),
        (
            "A-06",
            "Inspect env proxy vars",
            "Pip installation failures observed",
            "Root cause isolated",
        ),
        (
            "A-07",
            "Clear HTTP(S)_PROXY for pip",
            "Bypass SOCKS issue in local environment",
            "pip install succeeded",
        ),
        (
            "A-08",
            "Check existing repo config files",
            "Prevent conflicting setup assumptions",
            "Safe baseline for edits",
        ),
        (
            "A-09",
            "Initialize custom skill scaffold",
            "Need repo-specific engineering policy",
            "project-docling-engineer created",
        ),
        (
            "A-10",
            "Write custom SKILL.md",
            "Replace placeholders with actionable process",
            "Codified behavior",
        ),
        (
            "A-11",
            "Add skill references docs",
            "Keep SKILL concise and focused",
            "Progressive disclosure enabled",
        ),
        (
            "A-12",
            "Add skill quality script",
            "Reduce repeated manual checks",
            "One-command quality gate",
        ),
        (
            "A-13",
            "Validate skill folder",
            "Catch schema/frontmatter issues",
            "Skill confirmed valid",
        ),
        (
            "A-14",
            "Update pyproject dependencies",
            "Add rigorous tooling stack",
            "Lint/type/test tooling installed",
        ),
        (
            "A-15",
            "Add ruff and mypy config",
            "Enforce static quality baseline",
            "Deterministic analysis behavior",
        ),
        (
            "A-16",
            "Add .pre-commit-config.yaml",
            "Shift quality checks pre-commit",
            "Earlier error detection",
        ),
        (
            "A-17",
            "Add .editorconfig",
            "Editor-independent formatting consistency",
            "Reduced whitespace/style drift",
        ),
        ("A-18", "Add .gitignore", "Exclude generated/runtime noise", "Cleaner repo state"),
        (
            "A-19",
            "Add GitHub CI workflow",
            "Project-level quality enforcement",
            "Automated branch/PR validation",
        ),
        (
            "A-20",
            "Configure VS Code settings",
            "Consistent interpreter/test/lint behavior",
            "Lower local setup friction",
        ),
        (
            "A-21",
            "Add VS Code extension recommendations",
            "Standardize tooling footprint",
            "Predictable IDE features",
        ),
        ("A-22", "Add VS Code tasks", "Make common commands one-click", "Faster local loops"),
        (
            "A-23",
            "Add VS Code launch configs",
            "Enable reproducible debug entrypoints",
            "Improved troubleshooting",
        ),
        (
            "A-24",
            "Add Dev Container config",
            "Support reproducible isolated environment",
            "Portable containerized setup",
        ),
        (
            "A-25",
            "Add Dev Container Dockerfile",
            "Install OCR/system dependencies",
            "Container parity for doc pipeline",
        ),
        (
            "A-26",
            "Create bootstrap_dev.ps1",
            "Single-step Windows onboarding",
            "Automated local setup",
        ),
        (
            "A-27",
            "Create bootstrap_dev.sh",
            "Single-step Linux/macOS onboarding",
            "Cross-platform parity",
        ),
        (
            "A-28",
            "Create install_repo_skills.py",
            "Copy repo skill into local Codex",
            "Skill portability",
        ),
        (
            "A-29",
            "Create install_vscode_extensions.ps1",
            "Automate extension installation",
            "Less manual setup",
        ),
        (
            "A-30",
            "Fix extension identifier mismatch",
            "Install failed for invalid extension id",
            "Extension automation stabilized",
        ),
        (
            "A-31",
            "Update README with workflows",
            "Central user-facing operational guide",
            "Clear command discoverability",
        ),
        (
            "A-32",
            "Add tooling-research-notes.md",
            "Preserve source-backed decisions",
            "Auditability of choices",
        ),
        (
            "A-33",
            "Add implementation-playbook.md",
            "Standardize execution approach",
            "Reduced strategy drift",
        ),
        (
            "A-34",
            "Add multi-machine-setup.md",
            "Explicit clone-to-ready path",
            "Faster onboarding across systems",
        ),
        (
            "A-35",
            "Install dev dependencies",
            "Activate new tooling and editable package",
            "Local execution enabled",
        ),
        (
            "A-36",
            "Install optional analysis/fallback deps",
            "Prepare real Docling/OCR path",
            "Engine stack ready",
        ),
        (
            "A-37",
            "Install pre-commit hook",
            "Enforce checks automatically",
            "Hook active in .git/hooks",
        ),
        ("A-38", "Run ruff check", "Lint validation", "Passed"),
        ("A-39", "Run ruff format --check", "Formatting validation", "Passed"),
        ("A-40", "Run mypy", "Type validation", "Passed"),
        ("A-41", "Run pytest", "Automated test validation", "Passed"),
        ("A-42", "Run unittest fallback", "Additional smoke test path", "Passed"),
        (
            "A-43",
            "Run CLI --help",
            "Runtime command interface check",
            "Passed with expected commands",
        ),
        ("A-44", "Run quality gate script", "End-to-end local policy verification", "Passed"),
        ("A-45", "Run bootstrap script", "Validate reproducible setup command", "Passed"),
    ]
    table = document.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    header = table.rows[0].cells
    header[0].text = "ID"
    header[1].text = "Action"
    header[2].text = "Why"
    header[3].text = "Outcome"
    for action_id, action, why, outcome in actions:
        row = table.add_row().cells
        row[0].text = action_id
        row[1].text = action
        row[2].text = why
        row[3].text = outcome


def build_document() -> Document:
    document = Document()

    add_title(
        document,
        "Comprehensive Engineering Execution Report and Mind Map",
    )
    add_metadata(document)

    add_heading(document, "1. Objective and Intent", level=1)
    add_paragraph(
        document,
        (
            "This report documents the prior implementation in full depth: what was changed, "
            "why each step was taken, how decisions were made, what alternatives were considered, "
            "how risks were controlled, and how the final environment was validated for reliable "
            "project-context engineering execution."
        ),
    )
    add_bullet(
        document,
        "Primary intent: transform the coding environment from basic scaffold mode into a practical, repeatable, expert-level engineering workflow.",
    )
    add_bullet(
        document,
        "Secondary intent: maximize future session quality via skills, automation, validation gates, and cross-machine reproducibility.",
    )
    add_bullet(
        document,
        "Constraint respected: changes remained architecture-first for pipeline internals while strengthening process/tooling immediately.",
    )

    add_heading(document, "2. Request Decomposition and Reasoning Model", level=1)
    add_paragraph(
        document,
        (
            "The request was interpreted as a multi-objective systems task rather than a single code task. "
            "Execution was split into capability layers to avoid shallow improvements."
        ),
    )
    add_numbered(document, "Layer A: Skill intelligence (how Codex decides and behaves).")
    add_numbered(document, "Layer B: Toolchain reliability (pip, dependencies, quality tools).")
    add_numbered(document, "Layer C: Delivery ergonomics (VS Code, tasks, launch, extensions).")
    add_numbered(
        document, "Layer D: Team portability (GitHub CI + devcontainer + bootstrap scripts)."
    )
    add_numbered(document, "Layer E: Verification and evidence (lint/type/tests/CLI execution).")
    add_paragraph(
        document,
        (
            "Reasoning principle applied: improve system feedback loops first (tests, lint, CI, reproducible setup), "
            "then improve implementation velocity and consistency."
        ),
    )

    add_heading(document, "3. Skills Strategy and Why It Was Chosen", level=1)
    add_paragraph(
        document,
        "Skill use was mandatory and intentional because the task explicitly focused on improving execution quality and specialization.",
    )
    add_bullet(
        document,
        "Used skill-installer to discover installable curated skills and install high-value GitHub workflow skills.",
    )
    add_bullet(
        document,
        "Installed curated skills: gh-address-comments and gh-fix-ci.",
    )
    add_bullet(
        document,
        "Used skill-creator to generate and then harden a custom skill: project-docling-engineer.",
    )
    add_bullet(
        document,
        "Validated custom skill with quick_validate.py to avoid malformed trigger metadata.",
    )
    add_paragraph(
        document,
        (
            "Why this mattered: without explicit skill behavior, future sessions can regress into ad-hoc coding. "
            "The custom skill encodes repository-specific engineering discipline, quality gates, and Docling/RTL constraints."
        ),
    )

    add_heading(document, "4. Chronological Execution Timeline with Reason per Step", level=1)

    add_heading(document, "4.1 Discovery Phase", level=2)
    add_bullet(document, "Read skill-installer and skill-creator system skill instructions.")
    add_bullet(document, "Listed curated skills in JSON mode for deterministic automation.")
    add_bullet(
        document, "Checked current repo state, existing files, and VS Code baseline settings."
    )
    add_paragraph(
        document,
        "Reason: a reliable plan requires understanding starting conditions and available mechanisms before changes.",
    )

    add_heading(document, "4.2 Curated Skill Installation Phase", level=2)
    add_bullet(
        document,
        "Installed gh-address-comments (first pass succeeded).",
    )
    add_bullet(
        document,
        "Installed gh-fix-ci (second pass succeeded).",
    )
    add_bullet(
        document,
        "Re-listed skills to verify installed state.",
    )
    add_paragraph(
        document,
        "Reason: these skills strengthen practical repo maintenance cycles beyond coding itself (CI repair + PR completion discipline).",
    )

    add_heading(document, "4.3 Dependency Root-Cause Fix Phase", level=2)
    add_bullet(document, "Observed pip failure due to SOCKS/proxy setup.")
    add_bullet(document, "Inspected environment proxy variables.")
    add_bullet(
        document, "Temporarily cleared HTTP_PROXY and HTTPS_PROXY for package install commands."
    )
    add_bullet(document, "Confirmed package installation succeeds after this change.")
    add_paragraph(
        document,
        (
            "Reason: toolchain reliability is foundational. Without resolving install path instability, every other automation "
            "step would remain fragile across sessions and machines."
        ),
    )

    add_heading(document, "4.4 Project Skill Creation Phase", level=2)
    add_bullet(document, "Initialized skill scaffold using init_skill.py.")
    add_bullet(document, "Replaced placeholder SKILL.md with production workflow guidance.")
    add_bullet(
        document,
        "Added focused references: Docling implementation guide, engineering checklist, DOCX RTL notes.",
    )
    add_bullet(document, "Added reusable script: run_quality_gate.py.")
    add_bullet(document, "Validated skill schema.")
    add_paragraph(
        document,
        (
            "Reason: this encodes the decision model into reusable, versioned knowledge so future coding behavior stays consistent "
            "with architecture-first, tested implementation."
        ),
    )

    add_heading(document, "4.5 Repository and Toolchain Hardening Phase", level=2)
    add_bullet(
        document, "Extended pyproject.toml with dev dependencies and strict tool configuration."
    )
    add_bullet(document, "Added Ruff, mypy, pytest configuration and tuned for Typer CLI patterns.")
    add_bullet(document, "Added .gitignore, .editorconfig, and pre-commit hooks.")
    add_bullet(document, "Created bootstrap scripts for Windows and Linux/macOS.")
    add_bullet(document, "Created script to install repo-scoped skills into local Codex home.")
    add_paragraph(
        document,
        (
            "Reason: strong code comes from strong guardrails. Static checks and predictable setup reduce hidden failures and reduce variance between contributors."
        ),
    )

    add_heading(document, "4.6 VS Code and Developer Experience Integration Phase", level=2)
    add_bullet(document, "Configured interpreter/test/lint/format settings in workspace.")
    add_bullet(
        document, "Added extension recommendations and automated extension installation script."
    )
    add_bullet(document, "Added tasks and launch profiles for common operations.")
    add_bullet(
        document,
        "Fixed extension ID mismatch (python-environments -> ms-python.vscode-python-envs).",
    )
    add_paragraph(
        document,
        "Reason: practical engineering speed depends on short feedback loops and uniform editor behavior.",
    )

    add_heading(document, "4.7 GitHub and Portability Phase", level=2)
    add_bullet(document, "Added GitHub Actions CI for lint/format/test/CLI smoke.")
    add_bullet(
        document, "Added Dev Container with OCR/poppler support and post-create bootstrap command."
    )
    add_bullet(document, "Documented multi-machine bring-up process.")
    add_paragraph(
        document,
        (
            "Reason: changes must survive machine boundaries. CI and containerization reduce environment drift and onboarding friction."
        ),
    )

    add_heading(document, "4.8 Validation and Stabilization Phase", level=2)
    add_bullet(document, "Installed dev dependencies successfully in editable mode.")
    add_bullet(
        document,
        "Installed optional analysis/fallback dependencies successfully, including docling and pytesseract.",
    )
    add_bullet(
        document,
        "Ran ruff check, ruff format --check, mypy, pytest, unittest, and CLI help smoke test.",
    )
    add_bullet(document, "Executed project quality gate script end-to-end.")
    add_bullet(document, "Executed bootstrap script to prove reproducible setup path.")
    add_paragraph(
        document,
        (
            "Reason: completion is not code written, completion is code verified. This phase converted modifications into demonstrated operational readiness."
        ),
    )

    add_heading(document, "5. Mind Map of Decision System (What, Why, Outcome)", level=1)
    add_paragraph(
        document, "The following ASCII map captures the reasoning graph that drove execution:"
    )
    mind_map = r"""
ROOT: Become a practical expert engineering agent for this repository
|
+-- A. Skill Intelligence Layer
|   |
|   +-- Install curated skills (gh-fix-ci, gh-address-comments)
|   |   +-- Why: strengthen maintenance and review completion loops
|   |   +-- Outcome: better CI and PR workflow handling
|   |
|   +-- Create project-docling-engineer skill
|       +-- Why: encode project-specific engineering behavior
|       +-- Outcome: reusable decision policy for future sessions
|
+-- B. Reliability Layer
|   |
|   +-- Diagnose pip SOCKS/proxy issue
|   |   +-- Why: dependency installation was blocked
|   |   +-- Outcome: installs stabilized by clearing proxy vars in bootstrap
|   |
|   +-- Add lint/type/test gates
|       +-- Why: prevent silent regressions and weak code quality
|       +-- Outcome: deterministic quality checks and faster correction loops
|
+-- C. Workflow Layer
|   |
|   +-- VS Code settings/extensions/tasks/launch
|   |   +-- Why: reduce friction and manual command overhead
|   |   +-- Outcome: one-click run, test, lint, debug flows
|   |
|   +-- Pre-commit hooks
|       +-- Why: enforce standards before commit, not after failures
|       +-- Outcome: cleaner commit history and less CI churn
|
+-- D. Portability Layer
|   |
|   +-- Bootstrap scripts (Windows + Linux/macOS)
|   |   +-- Why: same setup logic on any machine
|   |   +-- Outcome: reproducible local onboarding
|   |
|   +-- Dev Container
|   |   +-- Why: eliminate host drift and system dependency mismatch
|   |   +-- Outcome: isolated reproducible environment
|   |
|   +-- GitHub CI
|       +-- Why: enforce quality in shared branch workflow
|       +-- Outcome: repository-level quality contract
|
+-- E. Domain Layer (Docling + Document Pipeline)
|   |
|   +-- Keep Docling as primary analysis path
|   |   +-- Why: align with requested architecture and modern extraction stack
|   |   +-- Outcome: cleaner primary analysis strategy
|   |
|   +-- Keep OCR/OpenCV fallback behind adapters
|   |   +-- Why: resilience when primary engine has gaps
|   |   +-- Outcome: controlled fallback without architectural leakage
|   |
|   +-- Preserve RTL/LTR metadata in IR and DOCX notes
|       +-- Why: Persian mixed-direction correctness is core requirement
|       +-- Outcome: implementation path remains aligned to language needs
|
+-- F. Verification Layer
    |
    +-- Run full quality gate + CLI smoke
        +-- Why: ensure execution reality matches intended architecture
        +-- Outcome: validated operational baseline
"""
    add_code_block(document, mind_map.strip())

    add_heading(document, "6. File-Level Change Matrix", level=1)
    add_paragraph(
        document,
        "This matrix enumerates key artifacts introduced or modified, with purpose and engineering value.",
    )
    add_file_table(document)

    add_heading(document, "7. Detailed Action Log (Step-by-Step)", level=1)
    add_paragraph(
        document,
        (
            "The table below captures the primary execution log as atomic decisions with explicit rationale. "
            "This is the operational mind-map flattened into actionable steps."
        ),
    )
    add_action_log_table(document)

    add_heading(document, "8. Web Research and Applied Decisions", level=1)
    add_paragraph(
        document,
        "Web research was used to avoid stale assumptions and align implementation with current tooling behavior.",
    )
    add_bullet(
        document,
        "Docling docs and examples were used to validate primary-engine strategy and OCR/table pipeline direction.",
    )
    add_bullet(
        document,
        "VS Code Python docs were used to set reliable testing/linting/formatting and interpreter behavior.",
    )
    add_bullet(
        document,
        "GitHub Actions setup-python docs informed CI matrix and pip cache strategy.",
    )
    add_bullet(
        document,
        "Ruff and pre-commit docs informed local quality gate and pre-commit enforcement design.",
    )
    add_paragraph(
        document,
        "Reference links were preserved in docs/tooling-research-notes.md for transparency and future updates.",
    )

    add_heading(document, "9. Verification Evidence Snapshot", level=1)
    add_bullet(document, "Ruff lint: passed.")
    add_bullet(document, "Ruff format check: passed.")
    add_bullet(document, "Mypy static type checking: passed.")
    add_bullet(document, "Pytest: passed (2 tests).")
    add_bullet(document, "Unittest smoke: passed.")
    add_bullet(document, "CLI help invocation: passed with required subcommands.")
    add_bullet(document, "Bootstrap script execution: passed.")
    add_bullet(document, "Docling import check: passed.")
    add_paragraph(document, "CLI help output observed:")
    add_code_block(
        document,
        """Usage: python -m docmirror [OPTIONS] COMMAND [ARGS]...
Commands:
  preprocess
  analyze
  render-docx
  validate
  run-all""",
    )

    add_heading(document, "10. Risk Register and Mitigations", level=1)
    add_bullet(
        document,
        "Risk: proxy-dependent package behavior can break installs. Mitigation: bootstrap scripts explicitly neutralize HTTP_PROXY/HTTPS_PROXY for install phase.",
    )
    add_bullet(
        document,
        "Risk: skill drift over time. Mitigation: project skill is versioned inside repo and installable via script.",
    )
    add_bullet(
        document,
        "Risk: environment drift across machines. Mitigation: devcontainer + bootstrap + CI checks.",
    )
    add_bullet(
        document,
        "Risk: premature implementation complexity in core OCR/rendering internals. Mitigation: architecture-first scaffolding with explicit TODO boundaries.",
    )

    add_heading(document, "11. Practical Conclusion", level=1)
    add_paragraph(
        document,
        (
            "The prior execution was not a blind code-writing pass; it was a systems-level hardening cycle. "
            "It improved decision quality (skills), implementation discipline (quality gates), developer ergonomics (VS Code tasks/launch), "
            "portability (bootstrap/devcontainer), and shared-repo reliability (CI). The environment is now configured to support "
            "wise, practical, and repeatable implementation of Python + Docling + document-generation work at higher engineering rigor."
        ),
    )

    add_heading(document, "12. Additional Context: Session Behavior Philosophy", level=1)
    add_bullet(
        document,
        "Do not implement everything at once when requirements include staged architecture and TODO boundaries.",
    )
    add_bullet(
        document,
        "Prefer interfaces/adapters to isolate high-volatility dependencies (Docling/OCR/OOXML internals).",
    )
    add_bullet(
        document,
        "Treat testability and reproducibility as first-order deliverables, not post-work cleanups.",
    )
    add_bullet(
        document,
        "Document not only what changed, but why each change exists and what failure mode it prevents.",
    )

    add_heading(document, "Appendix A - Key Commands Executed", level=1)
    commands = [
        "python .../skill-installer/scripts/list-skills.py --format json",
        "python .../skill-installer/scripts/install-skill-from-github.py --repo openai/skills --path skills/.curated/gh-fix-ci --path skills/.curated/gh-address-comments",
        ".\\.venv\\Scripts\\python .../skill-creator/scripts/init_skill.py project-docling-engineer --path .codex/skills --resources scripts,references ...",
        ".\\.venv\\Scripts\\python .../skill-creator/scripts/quick_validate.py .codex/skills/project-docling-engineer",
        ".\\.venv\\Scripts\\python -m pip install -e .[dev]",
        ".\\.venv\\Scripts\\python -m pip install -e .[analysis,fallback]",
        ".\\.venv\\Scripts\\python -m ruff check src tests ...",
        ".\\.venv\\Scripts\\python -m mypy src",
        ".\\.venv\\Scripts\\python -m pytest",
        "$env:PYTHONPATH='src'; .\\.venv\\Scripts\\python -m docmirror --help",
        "powershell -NoProfile -ExecutionPolicy Bypass -File scripts/bootstrap_dev.ps1 -ForceSkillOverwrite",
    ]
    for command in commands:
        add_code_block(document, command)

    add_heading(document, "Appendix B - External Source Links", level=1)
    links = [
        "https://docling-project.github.io/docling/examples/",
        "https://docling-project.github.io/docling/examples/full_page_ocr/",
        "https://docling-project.github.io/docling/examples/custom_convert/",
        "https://docling-project.github.io/docling/concepts/models/",
        "https://code.visualstudio.com/docs/python/settings-reference",
        "https://code.visualstudio.com/docs/python/testing",
        "https://code.visualstudio.com/docs/python/linting",
        "https://code.visualstudio.com/docs/python/formatting",
        "https://devblogs.microsoft.com/python/python-in-visual-studio-code-october-2025-release/",
        "https://github.com/actions/setup-python",
        "https://code.visualstudio.com/docs/devcontainers/containers",
        "https://containers.dev/",
        "https://pre-commit.com/",
        "https://docs.astral.sh/ruff/",
    ]
    for link in links:
        add_paragraph(document, link)

    section = document.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    return document


def main() -> None:
    output_dir = Path("output/doc")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "codex-engineering-upgrade-mindmap-report.docx"
    document = build_document()
    document.save(output_file)
    print(f"Wrote: {output_file}")


if __name__ == "__main__":
    main()
